title: Digits
description: A contact management system with notes and admin roles.
google_analytics:
show_downloads: false
theme: jekyll-theme-architect
github:
  is_project_page: true
  repository_url: https://arisa-1208.github.io/digits/
gems:
  - jekyll-mentions
